---
title: Rode klaver in rantsoenen
author: Albart Coster
date: '2018-08-16'
slug: rode-klaver-in-rantsoenen
categories: []
tags: [rode klaver, rantsoen, proteolyse]
banner: 'img/rode_klaver.jpg'
bibliography: [library.bib]
---

Het onderzoeksproject [Legumeplus](legumeplus.eu) is een groot europees onderzoek naar teelt en inzet van vlinderbloemige ruwvoergewassen. Een voordeel van vlinderbloemigen is dat ze stikstof uit de lucht fixeren, waardoor veel minder N bemesting nodig is (zie @DeWit2015). Daarnaast hebben  sommige vlinderbloemigen zoals rode klaver, sainfoin en rolklaver bevatten bioactieve stoffen die de eiwitbenutting kunnen verbeteren.

De gewassen Sainfoin en rolklaver bevatten gecondenseerde tannines (niet oplosbare tannines). Deze kunnen eiwit in de pens binden, waardoor het bestendiger wordt. Daarnaast hebben deze tannines een antiparasitaire werking. Rode klaver bevat het enzym *polyphenol oxidase*, dat afbraak van eiwit tijdens de aerobe fase van het gewas tegengaat. De effecten zijn substantieel, zie bijvoorbeeld tabel 3 uit @Copani2014. In dit onderzoek werden onderzoekskuilen gemaakt met Timothee, Sainfoin, en Rode klaver. De kuilen met Sainfoin en Rode klaver bevatten meer eiwit dan de kuil met Timothee (17.3%, 22.2% en 23.4%), maar veel minder oplosbaar eiwit (54.6%, 42%, 32.6%) en ook minder NH3 (16.8%, 13.6%, 7.6%). Dezelfde effecten van tannines en polyphenol oxidase werden gevonden in mengsels van Timothee met Sainfoin of Rode klaver. 

## Bronnen

